run:
  timeout: 5m
  build-tags:
    - cgo

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - typecheck
    - misspell
    - gofmt
    - goimports
  disable:
    - depguard
    - exhaustive
    - wrapcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    exclude-functions:
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Println
      - (io.Closer).Close
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/sgx-labs/statelessagent

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/web/static\.go
      linters:
        - goimports
  max-issues-per-linter: 50
  max-same-issues: 10
